name: Lint
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  conventional_commit:
    name: Conventional Commits
    if: ${{ github.ref != 'refs/heads/main' || github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ytanikin/PRConventionalCommits@1.1.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert","break"]'
  luacheck:
    name: Lua Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stevearc/nvim-typecheck-action@v1
        with:
          path: lua
          level: Information
          configpath: ".luarc.json"
          neodev-version: stable
      - uses: lunarmodules/luacheck@v1
        with:
          args: lua --config .luacheckrc
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --config-path .stylua.toml ./lua ./test
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.ref != 'refs/heads/main' || github.ref != 'refs/heads/master' }}
        with:
          commit_message: "chore(pr): auto-commit"
