name: LuaRocks
on:
  push:
    tags: # Will upload to luarocks.org when a tag is pushed
      - "*"
jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - uses: actions/checkout@v4
      - uses: nvim-neorocks/luarocks-tag-release@v5
        if: ${{ steps.release.outputs.release_created }}
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          name: linrongbin16-ci-template.nvim
          version: ${{ steps.release.outputs.tag_name }}
          labels: |
            neovim
            vim
