name: LuaRocks
on:
  push:
    tags:
      - "*"
jobs:
  upload-luarocks:
    runs-on: ubuntu-latest
    name: Upload LuaRocks
    steps:
      - uses: actions/checkout@v4
      - uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          name: linrongbin16-ci-template.nvim
          version: ${{ steps.release.outputs.tag_name }}
          labels: |
            neovim
            vim
